version: '3'
services:
  project-database:
    image: mongo:4.4.18-rc0-focal
    networks:
      - internal
    ports:
      - 30201:27017
    volumes:
      - /Users/anooppius/personal/learning/project/react-node-docker/data:/data/db
    environment:
      MONGO_INITDB_DATABASE: project-template
  project-ui:
    build:
      context: project-ui
      dockerfile: Dockerfile
    image: project-ui
    container_name: project-ui
    ports:
      - "3000:3000"
    networks:
      - internal
  project-external-api:
    build:
      context: project-external-api/.
      dockerfile: Dockerfile
    image: project-external-api
    container_name: project-external-api
    restart: always
    ports:
      - "3020:3020"
    networks:
      - internal
networks:
  internal:


